### ISSUE TITLE
Fails when  used with the themeswitcher plugin

### ISSUE THREAD

**Issue by sbillard** [RolandTi/collections#2]
Your functions.php file has active code for:

`zp_register_filter('themeSwitcher_head', 'switcher_head');
zp_register_filter('themeSwitcher_Controllink', 'switcher_controllink');
zp_register_filter('theme_head', 'css_head', 500);
`

But the target functions are not defined so if one uses themeswitcher to try out _collections_ a function not defined error is thrown. I suggest you comment out those lines until such time as you decide to implement switching functions, for instance the option to switch between light and dark versions.

I would also suggest that you edit the theme_description.php file and update the version number and date when you release new versions. This makes it easier to tell the difference between instances when, as I did, you place the new version in a differently named folder for testing purposes. I use the zenphoto derivative [netPhotoGraphics](https://github.com/netPhotoGraphics/netPhotoGraphics), so I have to make some edits to migrate the theme. So I don't want to discard the working version before testing the new one.

You have created a nice theme here. I look forward to its continued development.

**Comment by RolandTi** [comment]
Hello ! 
Thank you for your attention for this theme.
I fixed the two issues that you mentioned. And thanks again for your work on zenphoto too.
