### ISSUE TITLE
Horizontal thumbnails aren't centered

### ISSUE THREAD

**Issue by stalkerGH** [RolandTi/collections#4]
**What is going on:** Horizontally oriented images are displayed properly in gallery but they thumbnails not. Thumbnails are not centered; sometimes I see their left side and the right side is hidden, sometimes the opposite. Alignment top/bottom is good. See attached screenshots.
**Expected behaviour:** Center the thumbnail in such way that the center of every horizontal image is the center point of its square thumbnail.

ZenPhoto 1.6
Collections 1.1

![Screenshot_20230212_170313](https://user-images.githubusercontent.com/25331715/218322235-69754a8d-6c7c-4767-b46a-a93bb5445c94.jpg)

![Screenshot_20230212_113119](https://user-images.githubusercontent.com/25331715/218306172-7f5ea14f-6a3a-4b53-909a-9acb60aa19bf.jpg)

**Comment by RolandTi** [comment]
Hello, thanks for your remark. printCustomAlbumThumbImage fonction needs to be edited in album.php and gallery.php. Should take a minute but I need to take time to read the zenphoto doc. So maybe next week-end I'gonna to fix it.  Thank you again !

**Comment by stalkerGH** [comment]
I found description of this function here: https://docs.zenphoto.org/1.5.x/function-printCustomAlbumThumbImage.html but don't know how to use this knowledge :) I can't bound it with default values in theme's options in ZP admin panel so I'll wait for your free time...

**Comment by RolandTi** [comment]
Ok I've playing around with the function without success as you can see on my website. I'm going to vacation today,
I'll try to ask help on zenphoto forum next week.

![Capture d’écran 2023-02-14 101210](https://user-images.githubusercontent.com/28786873/218690735-07bf1a3e-985f-4265-a07d-67db93d6089c.png)

**Comment by RolandTi** [comment]
I asked for help here : https://forum.zenphoto.org/discussion/1411089/center-thumbnail/p1?new=1

**Comment by RolandTi** [comment]
Hello Stalker ! Thumbs have been fixed ! https://github.com/RolandTi/collections/releases/tag/v.1.2

**Comment by stalkerGH** [comment]
Thank you, it's working as expected now :)
