### ISSUE TITLE
head and header sections as separate files

### ISSUE THREAD

**Issue by kuz-z-zma** [RolandTi/collections#5]
It would be awesome to move head section and header to separate includes, as it will make adding Google Analytics code (and other stuff) and styling much easier for users.
Footer and navigation are already separate.

**Comment by RolandTi** [comment]
Hello ! I don't remember why I didn't split the header into a separate file. I will look to fix it next week, thanks for your note.

**Comment by kuz-z-zma** [comment]
> Hello ! I don't remember why I didn't split the header into a separate file.

That's why I was surprised - you did separate footer, but not the header. Weird!

Thanks for the fix, now it's much easier to work with

**Comment by RolandTi** [comment]
You're welcome
 :)
