### ISSUE TITLE
full size image view  & album/photo ordering

### ISSUE THREAD

**Issue by jtco42** [RolandTi/collections#7]
Hi, first off I really like the theme and am switching to it, but I'd like to tweak it a little bit.  My PHP is rusty so as of yet I haven't figured out how to do this and I don't know if this is something generally useful or not.

At a high level these issues/enhancements are: 
- I'd like to be able to click on the image to view the full size rather than go to next or prev picture. 
- Photo and Album ordering does not always follow the stated order - including manual order or by time
- It'd be nice to be able to force images to be shown before sub-albums in an album that has both.  This seems to be common to most themes, though zpBootstrap handles this.
- There also seems to be an oddity around how many images can show on a page with subalbums.  This may be more a zenphoto quirk.  For example I have one subalbum that has one subalbum in it and 40 photos.  This creates 2 pages, the first with the 1 subalbum and with 1 photo.  The next page has the remaining photos.

Again, the theme is great and I'll slowly poke some of it to see what I can get, but PHP/JS aren't my strong languages for me.

I'd have to admit that zpBootStrap fixes most of these for me, but I like the look of Collections - especially that it can show both title and descriptions on the thumbnail page. 

Thanks
John

**Comment by RolandTi** [comment]
Hello John, 
I missed your post, but here are my comments : 

>     * I'd like to be able to click on the image to view the full size rather than go to next or prev picture.

It's just some HTML, in image.php remove:
```				
# Overlay for nav, ONLY if photo
if ($_zp_current_image->isPhoto()) {
echo '<div class="overlay_nav_container">';
if (hasPrevImage()) { ?><a tabindex="-1" href="<?php echo html_encode(getPrevImageURL()); ?>" class="cursor_prev"></a><?php }
if (hasNextImage()) { ?><a tabindex="-1" href="<?php echo html_encode(getNextImageURL()); ?>" class="cursor_next"></a><?php }
if (!hasNextImage()) { ?><a tabindex="-1" href="<?php echo html_encode(getAlbumURL()); ?>" class="cursor_close"></a><?php }
echo '</div>';
}
```
and add a link around the `<img srcset="<?php echo html_encode` line 36, something like : 

```
<a href="<?php echo html_encode(getFullImageURL()); ?><img srcset="<?php echo html_encode(getCustomImageURL(NULL,2200,NULL,NULL,NULL,NULL,NULL,false,NULL)); ?>  2200w,
									<?php echo html_encode(getCustomImageURL(NULL,1280,NULL,NULL,NULL,NULL,NULL,false,NULL)); ?> 1280w,
				      		<?php echo html_encode(getCustomImageURL(NULL,640,NULL,NULL,NULL,NULL,NULL,false,NULL)); ?>  640w" 
				  sizes="100vw" 
				  src="<?php echo html_encode(getCustomImageURL(NULL,640,NULL,NULL,NULL,NULL,NULL,false,NULL)); ?>" 
				  alt="<?php echo getBareImageTitle(); ?>" 
				  width="<?php echo getFullWidth(); ?>"
				  height="<?php echo getFullHeight(); ?>" ></a>
```



>     * Photo and Album ordering does not always follow the stated order - including manual order or by time
Is it only on the Collections theme ? Because I don't manipulate anything, just using the offical loop.

>     * It'd be nice to be able to force images to be shown before sub-albums in an album that has both.  This seems to be common to most themes, though zpBootstrap handles this.
In album.php between line 33 & 43 you have to put the album loop after the `endwhile` on line 77.

>     * There also seems to be an oddity around how many images can show on a page with subalbums.  This may be more a zenphoto quirk.  For example I have one subalbum that has one subalbum in it and 40 photos.  This creates 2 pages, the first with the 1 subalbum and with 1 photo.  The next page has the remaining photos.
Yeah I now, It's making me crazy. I have to ask on Zenphoto forums.

> Again, the theme is great and I'll slowly poke some of it to see what I can get, but PHP/JS aren't my strong languages for me.
Thanks !
